LEVEL_SELECTION_BACKGROUND = "white"
LEVEL_SELECTION_TEXT_BACK = "black"
LEVEL_SELECTION_TEXT_BACK_HOVER = "red"
LEVEL_SELECTION_TEXT = "white"

ERROR_TEXT_COLOR = "red"
BACKGROUND_COLOR = "white"
NODE_END_COLOR = "#ffbb00"
NODE_UNIDSCOVERED_COLOR = "purple"
NODE_DONE_COLOR = "#7cbb00"
NODE_DISCOVERED_COLOR = "#f65314"

NODE_NAME_COLOR = "black"
NODE_HEURISTIC_COLOR = "#7cbb00"
NODE_ESTIMATED_TOTAL_COLOR = "#00a1f1"
NODE_NAME_BACKGROUND = "white"

PATH_FINAL_COLOR = "#ffbb00"
PATH_DONE = "#7cbb00"
PATH_OPEN = "black"
PATH_TEXT_COLOR = "black"

LEGEND_BACKGROUND = "white"
LEGEND_TEXT = "black"

FONT_SIZE = 15
NODE_TEXT_OFFSET = 0.05